FROM debian:trixie-slim

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      bc \
      bison \
      ca-certificates \
      flex \
      gcc \
      gcc-aarch64-linux-gnu \
      git \
      libelf-dev \
      libssl-dev \
      make \
 && rm -rf /var/lib/apt/lists/*
