"""Generate a 32-state plan YAML for *passive listening* mode.

SPK is silent (pattern: silence_2s + volume 0). All energy in the
recording comes from ambient sources (TV / room noise / HVAC). We sweep
through the 32 door states and capture 2 s of ambient noise filtered by
the house transfer function for each state. This tests whether the
classifier can recover door state from ambient excitation alone,
without driving the speaker.

Labels are sN where N is a 5-bit string ordered a b c AB BC: bit set →
OPEN, bit clear → CLOSE.

Usage:
    cd pc
    python plans/gen32_passive.py > plans/full_32_passive.yaml
"""
from __future__ import annotations

import sys

DOORS = ("a", "b", "c", "AB", "BC")
PATTERN_IDX = 2     # silence_2s — SPK emits 2 s of zeros
REPEATS     = 1
VOLUME      = 0     # ensure no SPK drive even if silence_2s ever picks up noise


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    out = sys.stdout
    out.write("# Auto-generated by plans/gen32_passive.py - 32 door states x 1 frame each.\n")
    out.write(f"# Pattern {PATTERN_IDX} (silence_2s, SPK silent), volume {VOLUME}, "
              f"{REPEATS} frame per state.\n")
    out.write("# Ambient TV / room noise is the natural excitation. Keep the TV (or\n")
    out.write("# whatever broadband source) running and stable during the entire run.\n")
    out.write("\n")
    for bits in range(32):
        flags = [(bits >> i) & 1 for i in range(5)]
        label_bits = "".join(str(f) for f in flags)
        label = f"s{label_bits}"
        out.write(f"- label: {label}\n")
        out.write(f"  pattern: {PATTERN_IDX}\n")
        out.write(f"  repeats: {REPEATS}\n")
        out.write(f"  volume: {VOLUME}\n")
        out.write("  doors: { ")
        out.write(", ".join(f"{d}: {'OPEN' if flags[i] else 'CLOSE'}"
                            for i, d in enumerate(DOORS)))
        out.write(" }\n")
        out.write("\n")


if __name__ == "__main__":
    main()
