"""v1 学習データ収集用の 32 状態 plan YAML を生成する。

gen32_noise.py と同じ 32 状態の網羅 (5 ドアの開閉組合せ全パターン) を、
1 状態あたり REPEATS フレーム繰り返して撮るための plan。Pattern は
noise_2s_prbs (PRBS 白色雑音、SPK 駆動) を使う — chirp / noise 比較で
noise 側の方が分散が小さく等価クラス間マージンが取れたため、本収集
方式として確定したもの。

ラベル規約は gen32.py / gen32_noise.py と同じ:
    sN ... N は 5 ビット文字列 (a b c AB BC の順、1 = OPEN、0 = CLOSE)

使い方:
    cd pc
    python plans/gen32_train.py > plans/full_32_train.yaml

実行:
    uv run python collector_client.py --port COM3 \
        --plan plans/full_32_train.yaml --run-id full_32_train_v1

実行時間目安: 32 状態 × (サーボ移動 + REPEATS × 2 s) ≒ 32 × 65 s ≒ 35 min。
途中で席を外したい場合は plan 実行中のコンソールでスペースキーを押せば
次のステップ境界で停止する (PauseController, もう一度押せば再開)。

patterns.yaml の並び替えがあった場合は PATTERN_IDX を要見直し。PAT INFO
で実機の現在の選択 idx も確認できる。
"""
from __future__ import annotations

import argparse
import sys

DOORS = ("a", "b", "c", "AB", "BC")
PATTERN_IDX = 4     # noise_2s_prbs (patterns.yaml の並びに依存)
DEFAULT_REPEATS = 30  # 1 状態あたりのフレーム数の既定値 (v1 本収集)
VOLUME      = 3     # ADC クリップしない実測上限付近 (5 だと 1.2 s 付近で乱れた)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate v1 train plan YAML for noise excitation.")
    ap.add_argument("--repeats", type=int, default=DEFAULT_REPEATS,
                    help=f"1 状態あたりのフレーム数 (既定 {DEFAULT_REPEATS})")
    args = ap.parse_args()
    repeats = args.repeats

    # 所要時間目安: 32 × (~1 s servo + repeats × 2 s) ≈ 32 × (1 + 2*repeats) sec
    est_min = (32 * (1 + 2 * repeats)) / 60.0

    # コンソール既定 (cp932 等) によらず UTF-8 で書き出す
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    out = sys.stdout
    out.write("# Auto-generated by plans/gen32_train.py — v1 本収集用 plan。\n")
    out.write(f"# Pattern {PATTERN_IDX} (noise_2s_prbs), volume {VOLUME}, "
              f"{repeats} frames/state. 32 states × {repeats} = "
              f"{32 * repeats} frames、所要時間 ~{est_min:.0f} min。\n")
    out.write("# SPK 励振方式なので TV / 環境音は不要 (むしろ静かな方が良い)。\n")
    out.write("\n")
    REPEATS = repeats  # for inline use below
    for bits in range(32):
        # ビット i は DOORS[i] に対応。a b c AB BC の順 (gen32.py と統一)。
        flags = [(bits >> i) & 1 for i in range(5)]
        label_bits = "".join(str(f) for f in flags)
        label = f"s{label_bits}"
        out.write(f"- label: {label}\n")
        out.write(f"  pattern: {PATTERN_IDX}\n")
        out.write(f"  repeats: {REPEATS}\n")
        out.write(f"  volume: {VOLUME}\n")
        out.write("  doors: { ")
        out.write(", ".join(f"{d}: {'OPEN' if flags[i] else 'CLOSE'}"
                            for i, d in enumerate(DOORS)))
        out.write(" }\n")
        out.write("\n")


if __name__ == "__main__":
    main()
