"""Generate a 32-state plan YAML using the white-noise excitation.

Same door enumeration as gen32.py (every (a, b, c, AB, BC) combination),
but pattern points at noise_2s_prbs in patterns.yaml so the recording
captures the room's stationary response to broadband stochastic excitation
instead of a Linear chirp.

Usage:
    cd pc
    python plans/gen32_noise.py > plans/full_32_noise.yaml

After generating, run:
    uv run python collector_client.py --port COM3 \
        --plan plans/full_32_noise.yaml --run-id full_32_noise_v1

Make sure the patterns.yaml ordering still places noise_2s_prbs at the
index referenced below (PATTERN_IDX). Re-check with `PAT INFO`.
"""
from __future__ import annotations

import sys

DOORS = ("a", "b", "c", "AB", "BC")
PATTERN_IDX = 4     # noise_2s_prbs in patterns.yaml (after the original 4 entries)
REPEATS     = 1
VOLUME      = 3     # keep low: noise excites all freqs at once


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    out = sys.stdout
    out.write("# Auto-generated by plans/gen32_noise.py - 32 door states x 1 frame each.\n")
    out.write(f"# Pattern {PATTERN_IDX} (noise_2s_prbs), volume {VOLUME}, "
              f"{REPEATS} frame per state. Total = 32 frames, ~3 min wall time.\n")
    out.write("# Companion to gen32.py / full_32.yaml; use --run-id full_32_noise_v1\n")
    out.write("# so the WAVs land in a separate folder from the chirp run.\n")
    out.write("\n")
    for bits in range(32):
        flags = [(bits >> i) & 1 for i in range(5)]
        label_bits = "".join(str(f) for f in flags)
        label = f"s{label_bits}"
        out.write(f"- label: {label}\n")
        out.write(f"  pattern: {PATTERN_IDX}\n")
        out.write(f"  repeats: {REPEATS}\n")
        out.write(f"  volume: {VOLUME}\n")
        out.write("  doors: { ")
        out.write(", ".join(f"{d}: {'OPEN' if flags[i] else 'CLOSE'}"
                            for i, d in enumerate(DOORS)))
        out.write(" }\n")
        out.write("\n")


if __name__ == "__main__":
    main()
