"""Generate a 32-state plan YAML — every combination of the 5 doors.

Each step records one frame (repeats: 1). Labels are sN where N is a
5-bit string ordered a b c AB BC: bit set → OPEN, bit clear → CLOSE.

Usage:
    cd pc
    python plans/gen32.py > plans/full_32.yaml

After generating, run:
    uv run python collector_client.py --port COM3 \
        --plan plans/full_32.yaml --run-id full_32_v1
"""
from __future__ import annotations

import sys

DOORS = ("a", "b", "c", "AB", "BC")
PATTERN_IDX = 1     # chirp_200_6k — change if patterns.yaml is reordered
REPEATS     = 1
VOLUME      = 3


def main() -> None:
    # Write UTF-8 to stdout regardless of the console's default cp932 etc.
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    out = sys.stdout
    out.write("# Auto-generated by plans/gen32.py - 32 door states x 1 frame each.\n")
    out.write(f"# Pattern {PATTERN_IDX} (chirp_200_6k), volume {VOLUME}, "
              f"{REPEATS} frame per state. Total = 32 frames, ~3 min wall time.\n")
    out.write("\n")
    for bits in range(32):
        # Bit i corresponds to DOORS[i]. Use bin order a b c AB BC.
        flags = [(bits >> i) & 1 for i in range(5)]
        label_bits = "".join(str(f) for f in flags)
        label = f"s{label_bits}"
        out.write(f"- label: {label}\n")
        out.write(f"  pattern: {PATTERN_IDX}\n")
        out.write(f"  repeats: {REPEATS}\n")
        out.write(f"  volume: {VOLUME}\n")
        out.write("  doors: { ")
        out.write(", ".join(f"{d}: {'OPEN' if flags[i] else 'CLOSE'}"
                            for i, d in enumerate(DOORS)))
        out.write(" }\n")
        out.write("\n")


if __name__ == "__main__":
    main()
