"""Factory baseline 生成: eval_noise_low の s00000 から代表 baseline を作る。

出力:
  - factory_baseline_noise_low.npy   : float32 array (1024,) PC 側参照用
  - factory_baseline_noise_low.h     : C ヘッダ (INT8 量子化済)
  - factory_baseline_meta.json       : 量子化パラメータ (scale, zero_point)

INT8 量子化方式:
  - 値の min/max を取って [-128, 127] にマップする per-tensor 量子化
  - 推論時に scale * (q - zero_point) で復元 → diff 計算に使う

Usage:
  cd pc
  uv run --extra training python generate_factory_baseline.py
"""
from __future__ import annotations

import json
import wave
from pathlib import Path

import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent / "training"))
from features import samples_to_logmag_psd


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "captures" / "eval_noise_low" / "s00000"
OUT_DIR = ROOT / "runs" / "factory_baseline"
HEADER_DIR = ROOT.parent / "firmware" / "projects" / "10_inference" / "source"


def main() -> int:
    # 1. eval_noise_low/s00000/frame_*.wav を全部 (10 frame) 読んで Welch log-mag 平均
    wavs = sorted(SRC.glob("frame_*.wav"))
    if not wavs:
        print(f"FAIL: no WAVs in {SRC}")
        return 2
    print(f"found {len(wavs)} frames in {SRC}")
    accum = None
    for p in wavs:
        with wave.open(str(p), "rb") as wf:
            rate = wf.getframerate()
            raw = wf.readframes(wf.getnframes())
        samples = np.frombuffer(raw, dtype=np.int16).astype(np.float32) / 32768.0
        db = samples_to_logmag_psd(samples)
        accum = db if accum is None else accum + db
    baseline = (accum / len(wavs)).astype(np.float32)
    print(f"baseline shape={baseline.shape}, min={baseline.min():.2f}, "
          f"max={baseline.max():.2f}, mean={baseline.mean():.2f}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    np.save(OUT_DIR / "factory_baseline_noise_low.npy", baseline)

    # 2. per-tensor INT8 量子化 (scale + offset 形式、ONNX の zero_point 規約は使わない)
    #    値の min..max を INT8 [-127, 127] にマップ (offset = center, scale = range/254)
    #    dequant: x = q * scale + offset
    lo, hi = float(baseline.min()), float(baseline.max())
    offset = (hi + lo) / 2.0          # range center
    scale = (hi - lo) / 254.0 if hi > lo else 1.0
    q = np.round((baseline - offset) / scale).astype(np.int32)
    q_clip = np.clip(q, -127, 127).astype(np.int8)
    dequant = q_clip.astype(np.float32) * scale + offset
    err = float(np.abs(baseline - dequant).max())
    print(f"INT8 quant: scale={scale:.6f}, offset={offset:.4f}, "
          f"max abs reconstruction error={err:.4f} dB")

    meta = {
        "source": str(SRC.relative_to(ROOT)),
        "n_frames_averaged": len(wavs),
        "shape": list(baseline.shape),
        "fp32_min": lo, "fp32_max": hi, "fp32_mean": float(baseline.mean()),
        "int8_scale": scale, "int8_offset": offset,
        "max_reconstruction_error_db": err,
        "encoding": "INT8 per-tensor (center + scale): x = q * scale + offset",
    }
    (OUT_DIR / "factory_baseline_meta.json").write_text(
        json.dumps(meta, indent=2, ensure_ascii=False))

    # 3. C ヘッダ生成
    HEADER_DIR.mkdir(parents=True, exist_ok=True)
    header_path = HEADER_DIR / "factory_baseline.h"
    lines = [
        "/* Auto-generated by pc/generate_factory_baseline.py — do not hand-edit.",
        " *",
        " * Factory-shipped baseline (eval_noise_low s00000 平均) INT8 量子化版。",
        " * 推論時に dequantize して 1024-bin log-mag spectrum から per-bin で引く。",
        " *",
        f" * Source: {meta['source']} ({meta['n_frames_averaged']} frames averaged)",
        f" * Range:  fp32 [{lo:.3f}, {hi:.3f}] dB (mean {meta['fp32_mean']:.3f})",
        f" * Quant:  scale={scale:.6f}, offset={offset:.4f}",
        f" * Max reconstruction error: {err:.4f} dB",
        " */",
        "#ifndef ICHP_FACTORY_BASELINE_H",
        "#define ICHP_FACTORY_BASELINE_H",
        "",
        "#include <stdint.h>",
        "",
        "#define ICHP_FACTORY_BASELINE_LEN 1024",
        f"#define ICHP_FACTORY_BASELINE_SCALE  ({scale:.6f}f)",
        f"#define ICHP_FACTORY_BASELINE_OFFSET ({offset:.6f}f)",
        "",
        "/* INT8 量子化値。dequant = q * SCALE + OFFSET → fp32 dB に復元。*/",
        "static const int8_t ichp_factory_baseline[ICHP_FACTORY_BASELINE_LEN] = {",
    ]
    # 16 値/行
    for i in range(0, len(q_clip), 16):
        chunk = q_clip[i:i + 16]
        line = "    " + ", ".join(f"{int(v):>4d}" for v in chunk) + ","
        lines.append(line)
    lines += [
        "};",
        "",
        "#endif /* ICHP_FACTORY_BASELINE_H */",
        "",
    ]
    header_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote artifacts:")
    print(f"  {OUT_DIR / 'factory_baseline_noise_low.npy'}")
    print(f"  {OUT_DIR / 'factory_baseline_meta.json'}")
    print(f"  {header_path}  ({header_path.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
